-- require("luasnip/loaders/from_vscode").load({paths=os.getenv("HOME") .. "/code/configs/pirate-vim/json"})
-- vim.o.runtimepath = vim.o.runtimepath .. "," .. os.getenv("HOME") .. "/code/configs/pirate-vim/json/snippets"
